[project]
name = "poet_chat"
version = "0.1.0"
description = "Fishjam voice agent example"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["fishjam-server-sdk", "openai-agents[voice]>=0.2.11"]

[tool.uv.sources]
fishjam-server-sdk = { workspace = true }
