[project]
name = "selective_subscription"
version = "0.1.0"
description = "Selective subscription demo"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["fishjam-server-sdk"]

[tool.uv.sources]
fishjam-server-sdk = { workspace = true }
