""".. include:: ../../docs/server_notifications.md"""

# Exported messages
from fishjam.events._protos.fishjam import (
    ServerMessageChannelAdded,
    ServerMessageChannelRemoved,
    ServerMessagePeerAdded,
    ServerMessagePeerConnected,
    ServerMessagePeerCrashed,
    ServerMessagePeerDeleted,
    ServerMessagePeerDisconnected,
    ServerMessagePeerMetadataUpdated,
    ServerMessagePeerType,
    ServerMessageRoomCrashed,
    ServerMessageRoomCreated,
    ServerMessageRoomDeleted,
    ServerMessageStreamConnected,
    ServerMessageStreamDisconnected,
    ServerMessageStreamerConnected,
    ServerMessageStreamerDisconnected,
    ServerMessageTrackAdded,
    ServerMessageTrackMetadataUpdated,
    ServerMessageTrackRemoved,
    ServerMessageViewerConnected,
    ServerMessageViewerDisconnected,
)
from fishjam.events._protos.fishjam.notifications import Track, TrackEncoding, TrackType

__all__ = [
    "ServerMessageRoomCreated",
    "ServerMessageRoomDeleted",
    "ServerMessageRoomCrashed",
    "ServerMessagePeerAdded",
    "ServerMessagePeerConnected",
    "ServerMessagePeerDeleted",
    "ServerMessagePeerDisconnected",
    "ServerMessagePeerMetadataUpdated",
    "ServerMessagePeerCrashed",
    "ServerMessageStreamConnected",
    "ServerMessageStreamDisconnected",
    "ServerMessageStreamerConnected",
    "ServerMessageStreamerDisconnected",
    "ServerMessageChannelAdded",
    "ServerMessageChannelRemoved",
    "ServerMessageTrackAdded",
    "ServerMessageTrackMetadataUpdated",
    "ServerMessageTrackRemoved",
    "ServerMessageViewerConnected",
    "ServerMessageViewerDisconnected",
    "Track",
    "TrackEncoding",
    "TrackType",
    "ServerMessagePeerType",
]
