from typing import Union

from fishjam.events import (
    ServerMessageChannelAdded,
    ServerMessageChannelRemoved,
    ServerMessagePeerAdded,
    ServerMessagePeerConnected,
    ServerMessagePeerCrashed,
    ServerMessagePeerDeleted,
    ServerMessagePeerDisconnected,
    ServerMessagePeerMetadataUpdated,
    ServerMessageRoomCrashed,
    ServerMessageRoomCreated,
    ServerMessageRoomDeleted,
    ServerMessageStreamerConnected,
    ServerMessageStreamerDisconnected,
    ServerMessageTrackAdded,
    ServerMessageTrackMetadataUpdated,
    ServerMessageTrackRemoved,
    ServerMessageViewerConnected,
    ServerMessageViewerDisconnected,
)

ALLOWED_NOTIFICATIONS = (
    ServerMessageRoomCreated,
    ServerMessageRoomDeleted,
    ServerMessageRoomCrashed,
    ServerMessagePeerAdded,
    ServerMessagePeerDeleted,
    ServerMessagePeerConnected,
    ServerMessagePeerDisconnected,
    ServerMessagePeerMetadataUpdated,
    ServerMessagePeerCrashed,
    ServerMessageStreamerConnected,
    ServerMessageStreamerDisconnected,
    ServerMessageChannelAdded,
    ServerMessageChannelRemoved,
    ServerMessageViewerConnected,
    ServerMessageViewerDisconnected,
    ServerMessageTrackAdded,
    ServerMessageTrackRemoved,
    ServerMessageTrackMetadataUpdated,
)

AllowedNotification = Union[
    ServerMessageRoomCreated,
    ServerMessageRoomDeleted,
    ServerMessageRoomCrashed,
    ServerMessagePeerAdded,
    ServerMessagePeerDeleted,
    ServerMessagePeerConnected,
    ServerMessagePeerDisconnected,
    ServerMessagePeerMetadataUpdated,
    ServerMessagePeerCrashed,
    ServerMessageStreamerConnected,
    ServerMessageStreamerDisconnected,
    ServerMessageChannelAdded,
    ServerMessageChannelRemoved,
    ServerMessageViewerConnected,
    ServerMessageViewerDisconnected,
    ServerMessageTrackAdded,
    ServerMessageTrackRemoved,
    ServerMessageTrackMetadataUpdated,
]
