name: docs

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/setup-uv@v6
        with:
          python-version-file: "pyproject.toml"
          enable-cache: true

      - run: uv sync --locked
      - run: uv run generate_docs
      - run: git fetch origin gh-pages --depth=1
      - run: git config user.name ci-bot
      - run: git config user.email ci-bot@example.com
      - run: uv run mike deploy ${{ github.ref_name }}
      - run: uv run mike set-default ${{ github.ref_name }}
      - run: git checkout gh-pages

      # Push changes to gh-pages branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
